# Generated by Django 3.1.1 on 2020-09-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_auto_20200918_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
