# Generated by Django 3.1.1 on 2020-09-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uniqueid',
        ),
    ]
