# Generated by Django 3.1.1 on 2020-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_auto_20200926_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Favourites',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
