# Generated by Django 3.1.1 on 2020-09-26 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0009_profile_favourites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Favourites',
        ),
    ]
