# Generated by Django 3.1.1 on 2020-09-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0011_auto_20200926_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='Favourites',
            new_name='favourites',
        ),
    ]
